- name: installing mysql
  hosts: mysql
  become: yes
  tasks:
  - name: install mysql
    ansible.builtin.dnf:
      name: mysql-server
      state: present

  - name: start mysql server
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: setup root passwd
    ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1